name: rebellion_rum_models
description: Central location to store data models for reuse in other projects
version: 1.0.0
repository: https://github.com/rknell/rebellion-rum-models
homepage: https://github.com/rknell/rebellion-rum-models
issue_tracker: https://github.com/rknell/rebellion-rum-models/issues

environment:
  sdk: ^3.6.0

dependencies:
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.0
  args: ^2.4.2
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  coverage: ^1.7.1
  test_process: ^2.1.0

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false