name: rebellion_rum_models
description: Central location to store data models for reuse in other projects
version: 1.0.0
publish_to: none
repository: https://github.com/rknell/rebellion_rum_models

environment:
  sdk: ^3.6.0

dependencies:
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.0
  args: ^2.4.2
  fixnum: ^1.1.0
  path: ^1.8.0
  logging: ^1.2.0
  alcocalc:
    git:
      url: git@github.com:rknell/alcocalc.git
      ref: main
  source_gen: ^2.0.0
  analyzer: ^7.3.0
  build: ^2.4.1
  

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  coverage: ^1.7.1
  test_process: ^2.1.0
  bson: ^5.0.5
  build_config: ^1.1.1
  http:

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false